meta:
  title: "Angular Meetup & builderscon 参加レポート"
  thumbnail:
  description: "2019/09/04 LT会"
  sns:
    - twitter
slide:
  loop: false
  sidebar: true
  targetBlank: true
  showIndex: true
  isVertical: false
  code:
    languages:
      - javascript
    plugins: []
    theme: default
  chart: false
  math: false
extends:
  js:
  css: ./style.css
  webpack:
build:
  ssr: true
